import { registerTab } from "./registry";
import { blankTab } from "./blank";
import { fileTreeTab } from "./file-tree";
import { gitTab } from "./git";
import { editorTab } from "./editor";
import { changesTab } from "./changes";
import { terminalTab } from "./terminal";
import { settingsTab } from "./settings";
import { infinityTab } from "./infinity";
import { searchTab } from "./search";
import { marketplaceTab } from "./marketplace";

registerTab(blankTab);
registerTab(editorTab);
registerTab(changesTab);
registerTab(fileTreeTab);
registerTab(gitTab);
registerTab(terminalTab);
registerTab(infinityTab);
registerTab(searchTab);
registerTab(marketplaceTab);
registerTab(settingsTab);

export { getTabDefinition, getAllTabDefinitions, getVisibleTabDefinitions } from "./registry";
export { registerTab } from "./registry";
export { unregisterTab } from "./registry";
export type { TabDefinition, TabContentProps } from "./types";
export { blankTab } from "./blank";
export { fileTreeTab } from "./file-tree";
export { gitTab } from "./git";
export { editorTab } from "./editor";
export { changesTab } from "./changes";
export { terminalTab } from "./terminal";
export { settingsTab } from "./settings";
export { infinityTab } from "./infinity";
export { searchTab } from "./search";
export { marketplaceTab } from "./marketplace";
